name: oth_apk
description: Online Treasure Hunt by Science Association

version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio:
  get_storage:
  flutter_dotenv:
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore:
  get: ^4.6.5
  location: ^5.0.3
  stop_watch_timer: ^1.3.1
  qr_code_scanner:
    git:
      url: https://github.com/X-SLAYER/qr_code_scanner.git
      ref: flutter-beta
  flutter_compass: ^0.8.0
  permission_handler: ^11.2.1
  flutter_native_splash: ^2.2.3
  flutter_launcher_icons: ^0.13.1
  flutter_vibrate: ^1.3.0
  flutter_image_slideshow: ^0.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter_native_splash:
  background_image: "assets/images/oth.png"


flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/oth_logo.png"




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
  #- images/a_dot_burr.jpeg
  # images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
