// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdvg80FoKCxrRJrNnHJZCmVqeHg9BPQCU',
    appId: '1:305380503193:web:03a3b89e993b620a1f9208',
    messagingSenderId: '305380503193',
    projectId: 'sa-oth-ada18',
    authDomain: 'sa-oth-ada18.firebaseapp.com',
    storageBucket: 'sa-oth-ada18.appspot.com',
    measurementId: 'G-7C0N7S4151',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6SRVVYJoSp79lU5w-YI50h7-Q_dct1_w',
    appId: '1:305380503193:android:b004b992e21eeb691f9208',
    messagingSenderId: '305380503193',
    projectId: 'sa-oth-ada18',
    storageBucket: 'sa-oth-ada18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOEVn3fENzlIXI3Iqokci5Z7xEoycgTL0',
    appId: '1:305380503193:ios:bc6cfdd1e615bd141f9208',
    messagingSenderId: '305380503193',
    projectId: 'sa-oth-ada18',
    storageBucket: 'sa-oth-ada18.appspot.com',
    iosClientId: '305380503193-tkev6pjqdk13i4okp9a6t20q3rrs4rr6.apps.googleusercontent.com',
    iosBundleId: 'com.ad.saOth',
  );
}
